version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - aws secretsmanager get-secret-value --secret-id ${DOCKER_HUB_TOKEN_KEY} --region us-east-1 --query SecretString --output text | docker login --username mapboxmachinereadonly --password-stdin
      - docker build -q -t ecs-watchbot -f test/Dockerfile ./
  build:
    commands:
      - docker run -t ecs-watchbot npm run test-container
