version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      docker build -q -t ecs-watchbot -f test/Dockerfile ./
  build:
    commands:
      - docker run -t ecs-watchbot npm run test-container