version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - docker build -q -t ecs-watchbot -f test/Dockerfile ./
  build:
    commands:
      - BUCKET_NAME=watchbot-binaries docker run -t ecs-watchbot npm run test-container
